name: Generate PDF CV

on:
  push:
    paths:
      - 'README.md'
      - 'cv.css'
  workflow_dispatch:

jobs:
  build-pdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Convert Markdown to PDF
        uses: BaileyJM02/markdown-to-pdf@v1
        with:
          input_path: README.md
          output_dir: pdf-output
          theme: cv.css
          extend_default_theme: false

      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Ian-King-CV
          path: pdf-output/README.pdf
