name: Generate PDF CV

on:
  push:
    paths:
      - README.md
      - pdf-style.css
      - config.json # Use your filename here
  workflow_dispatch:

jobs:
  build-pdf:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install md-to-pdf
      run: npm install -g md-to-pdf

    - name: Generate PDF from README.md
      run: md-to-pdf README.md --stylesheet pdf-style.css --config-file config.json

    - name: Upload PDF artifact
      uses: actions/upload-artifact@v4
      with:
        name: Ian-King-CV
        path: README.pdf